setwd("C:/A_E_Drive/20_Course_Certification/50_Getting_N_Cleaning_Data")
a<-read.table('household_power_consumption.txt', na.strings = '?',sep = ';',header = TRUE)
b<-a
b$Date<-strptime(b$Date, "%d/%m/%Y")
b$Date<-as.Date(b$Date)
c<-subset(b, Date == as.Date("2007-02-02") | Date == as.Date("2007-02-01"))
c$e<-as.POSIXlt(paste(c$Date,c$Time))
par(mfcol=c(2,2))
with(c,{plot(e,Global_active_power,type = 'l',xlab = '',ylab = 'Global Active Power (kilowatts)')
  plot(e,Sub_metering_1,type = 'l',xlab = '',ylab = 'Energy sub metering', col = 'black')
  lines(c$e,y=c$Sub_metering_2,type = 'l', col = 'red')
  lines(c$e,y=c$Sub_metering_3,type = 'l', col = 'blue')
  legend('topright',lty = 1,col=c('black','red','blue'),legend = c('Sub_metering_1','Sub_metering_2','Sub_metering_3'))
  plot(e,Voltage,type = 'l',xlab = 'datetime', col = 'black')
  plot(e,Global_reactive_power,type = 'l',xlab = 'datetime', col = 'black')
})
dev.copy(png,file='plot4.png')
dev.off()